language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install:
  - npm install universal-cookies --save
script:
  - npm test
  - npm run build
  - npm run test:coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GitHub_Token
  local_dir: build
  on:
    branch: master
